### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../models/xlnet_1024_bs_8_adamw_data_80_lr_2e05_20'

### ISSUE THREAD

**Issue by swerizwan** [yudhik11/MER-lyrics-Transformer#1]
I am getting that error while executing run.py
FileNotFoundError: [Errno 2] No such file or directory: '../models/xlnet_1024_bs_8_adamw_data_80_lr_2e05_20'

**Comment by theo-mo** [comment]
hello, i am wondering where can i get the moodylyrics datasets, because i've search it on the Internet and all the results show that there is no "moodylyrics.csv" formation file

**Comment by yudhik11** [comment]
It can downloaded from http://softeng.polito.it/erion/MoodyLyrics.zip.
